name: introduction_screen
description: Introduction/Onboarding package for flutter app with some customizations possibilities
version: 1.0.9
homepage: https://github.com/pyozer/introduction_screen

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dots_indicator: ^1.2.0
  flutter_staggered_animations: 
    git:
      url: git://github.com/Cybernetics354/flutter_staggered_animations.git
      ref: master
